#! /usr/bin/env bash
set -euo pipefail
main_class="sql_evaluator.Main"

# Locate the script file.  Cross symlinks if necessary.
loc="$0"
while [ -h "$loc" ]; do
    ls=`ls -ld "$loc"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        loc="$link"  # Absolute link
    else
        loc="$(dirname "$loc")/$link"  # Relative link
    fi
done
base_dir="$(dirname "$loc")"

classpath_file="$base_dir/target/runtime-classpath"
if [[ ! -f "$classpath_file" ]]; then
    echo "Missing \"$classpath_file\".  Did you run \"mvn compile\" yet?" > /dev/stderr
    exit 1
fi

classpath="$base_dir/target/classes:$(cat "$classpath_file")"

exec java -ea -cp "$classpath" "$main_class" "$@"
